name: Desktop Production Release

on:
  workflow_dispatch: # Allows you to manually trigger the build from the GitHub Actions tab
  push:
    tags:
      - 'v*' # Automatically triggers when you push a tag like "v1.0.0"

jobs:
  build-windows:
    name: Build Windows MSI
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          # Disabled cache on Windows to prevent tar.exe error

      - name: Build Windows Installer (MSI)
        run: ./gradlew.bat :composeApp:packageReleaseMsi

      - name: Rename MSI file
        run: |
          cd composeApp/build/compose/binaries/main-release/msi/
          mv *.msi SecureQuickTransfer-Setup.msi
        shell: bash

      - name: Upload Windows MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SecureQuickTransfer
          path: composeApp/build/compose/binaries/main-release/msi/SecureQuickTransfer-Setup.msi
          retention-days: 7

  build-linux:
    name: Build Linux DEB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Linux Installer (DEB)
        run: ./gradlew :composeApp:packageReleaseDeb

      - name: Rename DEB file
        run: |
          cd composeApp/build/compose/binaries/main-release/deb/
          mv *.deb SecureQuickTransfer-Setup.deb
        shell: bash

      - name: Upload Linux DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SecureQuickTransfer-Linux
          path: composeApp/build/compose/binaries/main-release/deb/SecureQuickTransfer-Setup.deb
          retention-days: 7
